### ISSUE TITLE
REST API running in Docker container does not automatically "trust" requests from host machine

### ISSUE THREAD

**Issue by tdonohue** [DSpace/DSpace#3229]
**Describe the bug**
Discovered while testing https://github.com/DSpace/dspace-angular/pull/1004 (with #3223). 

When running the DSpace REST API in a Docker container, the host machine will not be automatically "trusted".  This is because requests from the host machine will not be seen as localhost requests (127.0.0.1), and instead will appear from the Docker network's gateway/bridge IP.  

Docker seems to choose the next available subnet/IP range starting with `172.17.0.0`...when using that subnet, requests from the host to the container will appear under the first IP address in that range (i.e. `172.17.0.1`).  These requests will be blocked in any scenarios which require the IP to be in the list of `proxies.trusted.ipranges`.

**To Reproduce**
1. Start the REST API in Docker
2. Access it in your browser from the host machine
3. Login to the Docker machines & verify the Tomcat logs show the requests coming from an internal IP address starting with 172.
   ```
   docker exec -it dspace /bin/bash
   more /usr/local/tomcat/logs/localhost_access_log*
   ```
4. That same IP address will be the default ethernet gateway address on the Docker container
    ```
    docker exec -it dspace /bin/bash
    /sbin/ip route
    ```

**Expected behavior**
When running the REST API from a Docker container, ideally we should automatically *trust* requests coming from the host machine.  

It appears this might be most easily achieved via tweaking our `docker-compose.yml` configuration, like this:
```
networks:
  dspacenet:
    ipam:
      config:
        # Define a custom subnet for our DSpace network, so that we can easily trust requests from host to container.
        # If you customize this value, be sure to customize the 'proxies.trusted.ipranges' in your local.cfg.
        - subnet: 172.23.0.0/16
```

Once we specify the `subnet`, we know that the first available IP (or all IPs in that range) can be trusted.  So, we can modify the default Docker `local.cfg` to say:
```
# This is the first IP address in the 'dspacenet' subnet. In Docker this will be the gateway/bridge IP.
# We must trust this IP in order to trust all requests from the host machine to the Docker container.
proxies.trusted.ipranges = 172.23.0.1

# NOTE: we could also choose to trust the entire Docker network subnet as follows
# proxies.trusted.ipranges = 172.23.0
```
(NOTE: While I show two options above, I'm starting to lean towards trusting the entire subnet...the second option.  Will do further testing though when the PR is created to verify.)

The only risk to this approach is that it's **possible** some users could already be using the configured subnet.  

However, in that scenario, they could change these two settings to a different value which works for their environment.  This is no different than potentially having to change the default `ports` also specified in our `docker-compose.yml`.
